import type { Metadata } from 'next'
import { Inter,Lalezar } from 'next/font/google'
import Image from 'next/image';
import Link from 'next/link';
import './globals.css'
import styls from "./Containfood.module.css";
import Navbar from '../component/nav/navbar'
import Header from '../component/header/header'
import { Suspense } from 'react'
import { NavigationEvents } from '@/component/navigation-events'
const inter = Inter({ subsets: ['latin'] })
const lalezar = Lalezar({
  subsets: ['arabic'],
  weight: '400'
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
     
        <Navbar/>
 
        <Header/>
     
        <div className={styls.containfood}>
        <div className={styls.category}>
         {children}
         </div>
         
        <div  className={styls.groupbasket}>
        <h1 className={styls.tit}>السلة</h1>
        <div className={styls.basket}>
        <Suspense fallback={null}>
          <NavigationEvents />
        </Suspense>
        </div>
    
        <div>
   
    </div>


         </div>
</div>
        
        </body>
    </html>
  )
}
